### ISSUE TITLE
Import de lieu en local : fopen - failed to open stream: Permission denied

### ISSUE THREAD

**Issue by pduthoit** [Machu96/projet-quartier-v2#19]
Yo Maxime j'ai cette erreur quand j'essaye d'uploader un lieu et notamment une image depuis mon ordinateur en local.

fopen(C:\Users\User\Desktop\hubiC\Institut G4\Projet-quartier\projet-quartier-v2\public): failed to open stream: Permission denied

![image](https://cloud.githubusercontent.com/assets/9465766/20939175/09a10d38-bbee-11e6-8627-f41aa9313cb5.png)

Il doit y avoir un soucis au niveau du path d'un fopen. Tu saurais d'où ça pourrait venir ?
Merci

**Comment by jean-smaug** [comment]
Absolument aucune idée :/ @RochezBaptiste  tu as l'erreur toi aussi ? peut être de xampp

**Comment by RochezBaptiste** [comment]
essaye ça
chmod -R gu+w storage

chmod -R guo+w storage

php artisan cache:clear

**Comment by RochezBaptiste** [comment]
J'ai le même problème si jamais, et dans le cmd la commande chmod est inconnu lol
Dit moi si ça marche pour toi @pduthoit
